# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:36
from __future__ import unicode_literals

from django.db import migrations


def set_development_site(apps, schema_editor):
	Site = apps.get_model('sites', 'Site')
	current= Site.objects.create(domain='localhost:8000',name="Django-Angular-Webpack-Starter")
	current.save()

class Migration(migrations.Migration):

    dependencies = [
    	('sites', '0002_alter_domain_unique')
    ]

    operations = [
    	migrations.RunPython(set_development_site),
    ]
