# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_resetpasswordrequest_useractivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
